import { orderedSections, sectionHasContent, SECTION_HEADINGS, type Resume } from "@/lib/schema";
import { bulletsEnv, contactParts, month, range, README, tex, type LatexOutput } from "./common";

/**
 * "Banking" style: understated serif (Charter), letterspaced name over a thin rule,
 * uppercase section labels.
 */
export function renderBanking(r: Resume): LatexOutput {
  const paper = r.meta.paper === "a4" ? "a4paper" : "letterpaper";
  const body = orderedSections(r)
    .filter((s) => sectionHasContent(r, s))
    .map((s) => section(s, r))
    .join("\n");

  const texSrc = `%% Resume, "Banking" style, generated by ResumeFold
%% Compile with pdflatex.
\\documentclass[${paper},10.5pt]{article}

\\usepackage[margin=0.7in,top=0.6in,bottom=0.6in]{geometry}
\\usepackage[T1]{fontenc}
\\usepackage[utf8]{inputenc}
\\usepackage{charter}
\\usepackage{xcolor}
\\usepackage{titlesec}
\\usepackage{enumitem}
\\usepackage{tabularx}
\\usepackage{microtype}
\\usepackage[hidelinks]{hyperref}
\\input{glyphtounicode}
\\pdfgentounicode=1

\\definecolor{muted}{HTML}{444444}
\\pagestyle{empty}
\\setlength{\\parindent}{0pt}
\\setlength{\\tabcolsep}{0pt}
\\raggedbottom
\\urlstyle{same}

\\titleformat{\\section}{\\normalsize\\bfseries\\scshape}{}{0em}{\\MakeUppercase}[\\vspace{-4pt}\\rule{\\textwidth}{0.4pt}]
\\titlespacing*{\\section}{0pt}{11pt}{5pt}

\\newcommand{\\vEntry}[4]{%
  \\begin{tabular*}{\\textwidth}{@{}l@{\\extracolsep{\\fill}}r@{}}
    \\textbf{#1} & #2\\\\
    \\textit{#3} & \\textit{#4}\\\\
  \\end{tabular*}\\par}
\\newcommand{\\vEntryOne}[2]{%
  \\begin{tabular*}{\\textwidth}{@{}l@{\\extracolsep{\\fill}}r@{}}
    #1 & #2\\\\
  \\end{tabular*}\\par}
\\newenvironment{vBullets}{\\begin{itemize}[leftmargin=1.2em,itemsep=0pt,topsep=2pt,label=--]}{\\end{itemize}\\vspace{3pt}}
\\newcommand{\\vGap}{\\vspace{4pt}}

\\begin{document}

% ---- header ----
\\begin{center}
  {\\fontsize{20}{24}\\selectfont\\scshape\\textls[120]{${tex(r.contact.fullName)}}}\\\\[3pt]
  ${r.contact.headline ? `{\\itshape ${tex(r.contact.headline)}}\\\\[3pt]` : ""}
  {\\small\\color{muted} ${contactParts(r).join(" \\hspace{5pt}\\textbullet\\hspace{5pt} ")}}\\\\[2pt]
  \\rule{\\textwidth}{0.6pt}
\\end{center}

${body}
\\end{document}
`;

  return { files: { "resume.tex": texSrc, "README.md": README("Banking", "pdflatex") }, main: "resume.tex", engine: "pdflatex" };
}

function section(id: ReturnType<typeof orderedSections>[number], r: Resume): string {
  const H = `\\section{${SECTION_HEADINGS[id]}}\n`;
  switch (id) {
    case "summary":
      return `${H}${tex(r.summary)}\\par\\vGap\n`;
    case "experience":
      return (
        H +
        r.experience
          .map(
            (e) =>
              `\\vEntry{${tex(e.title)}}{${range(e.start, e.end, e.current)}}{${tex(e.company)}}{${tex(e.location)}}\n` +
              (bulletsEnv(e.bullets, "vBullets", "") || "\\vGap\n"),
          )
          .join("")
      );
    case "education":
      return (
        H +
        r.education
          .map((e) => {
            const deg = [e.degree, e.field].filter(Boolean).join(" in ") + (e.gpa ? `, GPA ${e.gpa}` : "");
            return `\\vEntry{${tex(e.school)}}{${range(e.start, e.end)}}{${tex(deg)}}{${tex(e.location)}}\n` + (bulletsEnv(e.details, "vBullets", "") || "\\vGap\n");
          })
          .join("")
      );
    case "skills":
      return (
        H +
        r.skills
          .filter((g) => g.items.length)
          .map((g) => `${g.category ? `\\textbf{${tex(g.category)}:} ` : ""}${tex(g.items.join(", "))}\\par\n`)
          .join("") +
        "\\vGap\n"
      );
    case "projects":
      return (
        H +
        r.projects
          .map((p) => {
            const title = `\\textbf{${tex(p.name)}}${p.tech ? ` --- \\textit{${tex(p.tech)}}` : ""}`;
            const right = range(p.start, p.end) || tex(p.link);
            return `\\vEntryOne{${title}}{${right}}\n` + (bulletsEnv(p.bullets, "vBullets", "") || "\\vGap\n");
          })
          .join("")
      );
    case "certifications":
      return (
        H +
        r.certifications
          .map((c) => `\\vEntryOne{\\textbf{${tex(c.name)}}${c.issuer ? `, ${tex(c.issuer)}` : ""}}{${month(c.date)}}\n`)
          .join("") +
        "\\vGap\n"
      );
  }
}
