import { orderedSections, sectionHasContent, SECTION_HEADINGS, type Resume } from "@/lib/schema";
import { bulletsEnv, contactParts, month, range, README, tex, type LatexOutput } from "./common";

/**
 * "Bold" style: a large light/heavy name, one accent colour on section titles
 * and dates, Source Sans.
 */
export function renderBold(r: Resume): LatexOutput {
  const paper = r.meta.paper === "a4" ? "a4paper" : "letterpaper";
  const [first, ...rest] = r.contact.fullName.trim().split(/\s+/);
  const last = rest.join(" ");
  const body = orderedSections(r)
    .filter((s) => sectionHasContent(r, s))
    .map((s) => section(s, r))
    .join("\n");

  const texSrc = `%% Resume, "Bold" style, generated by ResumeFold
%% Compile with pdflatex.
\\documentclass[${paper},10pt]{article}

\\usepackage[margin=0.55in,top=0.5in,bottom=0.5in]{geometry}
\\usepackage[T1]{fontenc}
\\usepackage[utf8]{inputenc}
\\usepackage[default,semibold]{sourcesanspro}
\\usepackage{xcolor}
\\usepackage{titlesec}
\\usepackage{enumitem}
\\usepackage{tabularx}
\\usepackage{microtype}
\\usepackage[hidelinks]{hyperref}
\\input{glyphtounicode}
\\pdfgentounicode=1

\\definecolor{accent}{HTML}{C7522A}
\\definecolor{muted}{HTML}{5E5A52}
\\definecolor{hair}{HTML}{BDB8AE}

\\pagestyle{empty}
\\setlength{\\parindent}{0pt}
\\setlength{\\tabcolsep}{0pt}
\\raggedbottom
\\urlstyle{same}

% ---- section: accent title, hairline ----
\\titleformat{\\section}{\\Large\\bfseries\\color{accent}}{}{0em}{}[{\\color{hair}\\titlerule[0.8pt]}\\vspace{-3pt}]
\\titlespacing*{\\section}{0pt}{10pt}{6pt}

% ---- entries ----
\\newcommand{\\vEntry}[4]{%
  \\begin{tabular*}{\\textwidth}{@{}l@{\\extracolsep{\\fill}}r@{}}
    {\\bfseries\\large #1} & {\\itshape\\color{accent}#2}\\\\
    {\\color{muted}#3} & {\\color{muted}\\small #4}\\\\
  \\end{tabular*}\\par}
\\newcommand{\\vEntryOne}[2]{%
  \\begin{tabular*}{\\textwidth}{@{}l@{\\extracolsep{\\fill}}r@{}}
    #1 & {\\itshape\\color{accent}#2}\\\\
  \\end{tabular*}\\par}
\\newenvironment{vBullets}{\\begin{itemize}[leftmargin=1.1em,itemsep=0pt,topsep=2pt,label=\\textbullet]}{\\end{itemize}\\vspace{4pt}}
\\newcommand{\\vGap}{\\vspace{5pt}}

\\begin{document}

% ---- header ----
\\begin{center}
  {\\fontsize{28}{32}\\selectfont {\\fontseries{l}\\selectfont ${tex(first ?? "")}} {\\bfseries ${tex(last)}}}\\\\[2pt]
  ${r.contact.headline ? `{\\color{accent}\\scshape\\small ${tex(r.contact.headline)}}\\\\[4pt]` : ""}
  {\\small\\color{muted} ${contactParts(r).join(" \\hspace{5pt}{\\color{hair}\\textbar}\\hspace{5pt} ")}}
\\end{center}
\\vspace{2pt}

${body}
\\end{document}
`;

  return { files: { "resume.tex": texSrc, "README.md": README("Bold", "pdflatex") }, main: "resume.tex", engine: "pdflatex" };
}

function section(id: ReturnType<typeof orderedSections>[number], r: Resume): string {
  const H = `\\section{${SECTION_HEADINGS[id]}}\n`;
  switch (id) {
    case "summary":
      return `${H}${tex(r.summary)}\\par\\vGap\n`;
    case "experience":
      return (
        H +
        r.experience
          .map(
            (e) =>
              `\\vEntry{${tex(e.title)}}{${range(e.start, e.end, e.current)}}{${tex(e.company)}}{${tex(e.location)}}\n` +
              (bulletsEnv(e.bullets, "vBullets", "") || "\\vGap\n"),
          )
          .join("")
      );
    case "education":
      return (
        H +
        r.education
          .map((e) => {
            const deg = [e.degree, e.field].filter(Boolean).join(" in ") + (e.gpa ? `, GPA ${e.gpa}` : "");
            return `\\vEntry{${tex(e.school)}}{${range(e.start, e.end)}}{${tex(deg)}}{${tex(e.location)}}\n` + (bulletsEnv(e.details, "vBullets", "") || "\\vGap\n");
          })
          .join("")
      );
    case "skills":
      return (
        H +
        r.skills
          .filter((g) => g.items.length)
          .map((g) => `${g.category ? `\\textbf{${tex(g.category)}:} ` : ""}${tex(g.items.join(", "))}\\par\n`)
          .join("") +
        "\\vGap\n"
      );
    case "projects":
      return (
        H +
        r.projects
          .map((p) => {
            const title = `\\textbf{${tex(p.name)}}${p.tech ? ` {\\color{muted}--- ${tex(p.tech)}}` : ""}`;
            const right = range(p.start, p.end) || tex(p.link);
            return `\\vEntryOne{${title}}{${right}}\n` + (bulletsEnv(p.bullets, "vBullets", "") || "\\vGap\n");
          })
          .join("")
      );
    case "certifications":
      return (
        H +
        r.certifications
          .map((c) => `\\vEntryOne{\\textbf{${tex(c.name)}}${c.issuer ? `, ${tex(c.issuer)}` : ""}}{${month(c.date)}}\n`)
          .join("") +
        "\\vGap\n"
      );
  }
}
