import { orderedSections, sectionHasContent, SECTION_HEADINGS, type Resume } from "@/lib/schema";
import { bulletsEnv, contactParts, month, range, README, tex, type LatexOutput } from "./common";

/**
 * "Classic" style: dense, small-caps section titles over a rule, dates right-aligned.
 */
export function renderClassic(r: Resume): LatexOutput {
  const paper = r.meta.paper === "a4" ? "a4paper" : "letterpaper";
  const body = orderedSections(r)
    .filter((s) => sectionHasContent(r, s))
    .map((s) => section(s, r))
    .join("\n");

  const texSrc = `%% Resume, "Classic" style, generated by ResumeFold
%% Compile with pdflatex.
\\documentclass[${paper},11pt]{article}

\\usepackage[margin=0.5in,top=0.45in,bottom=0.45in]{geometry}
\\usepackage[T1]{fontenc}
\\usepackage[utf8]{inputenc}
\\usepackage{lmodern}
\\usepackage{xcolor}
\\usepackage{titlesec}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{tabularx}
\\usepackage{microtype}
\\input{glyphtounicode}
\\pdfgentounicode=1            % ATS: make the PDF text extractable

\\pagestyle{empty}
\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}
\\setlength{\\parindent}{0pt}
\\urlstyle{same}

% ---- section heading: small caps, rule beneath ----
\\titleformat{\\section}{\\vspace{-4pt}\\scshape\\raggedright\\large}{}{0em}{}[\\color{black}\\titlerule\\vspace{-5pt}]

% ---- entry macros ----
\\newcommand{\\vEntry}[4]{%
  \\vspace{-1pt}\\item
  \\begin{tabular*}{\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
    \\textbf{#1} & #2 \\\\
    \\textit{\\small#3} & \\textit{\\small#4} \\\\
  \\end{tabular*}\\vspace{-4pt}}
\\newcommand{\\vEntryOne}[2]{%
  \\item
  \\begin{tabular*}{\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
    \\small#1 & #2 \\\\
  \\end{tabular*}\\vspace{-4pt}}
\\newcommand{\\vLine}[1]{\\item\\small{#1\\vspace{-2pt}}}
\\newenvironment{vEntries}{\\begin{itemize}[leftmargin=0.15in,label={}]}{\\end{itemize}}
\\newenvironment{vBullets}{\\begin{itemize}[leftmargin=0.15in,itemsep=-1pt,topsep=1pt]}{\\end{itemize}\\vspace{-5pt}}

\\begin{document}

% ---- header ----
\\begin{center}
  {\\Huge\\scshape ${tex(r.contact.fullName)}}\\\\[3pt]
  \\small ${contactParts(r).join(" $|$ ")}
\\end{center}

${body}
\\end{document}
`;

  return { files: { "resume.tex": texSrc, "README.md": README("Classic", "pdflatex") }, main: "resume.tex", engine: "pdflatex" };
}

function section(id: ReturnType<typeof orderedSections>[number], r: Resume): string {
  const H = `\\section{${SECTION_HEADINGS[id]}}\n`;
  switch (id) {
    case "summary":
      return `${H}\\small ${tex(r.summary)}\\par\\vspace{2pt}\n`;
    case "experience":
      return (
        H +
        "\\begin{vEntries}\n" +
        r.experience
          .map(
            (e) =>
              `  \\vEntry{${tex(e.title)}}{${range(e.start, e.end, e.current)}}{${tex(e.company)}}{${tex(e.location)}}\n` +
              bulletsEnv(e.bullets, "vBullets"),
          )
          .join("") +
        "\\end{vEntries}\n"
      );
    case "education":
      return (
        H +
        "\\begin{vEntries}\n" +
        r.education
          .map((e) => {
            const deg = [e.degree, e.field].filter(Boolean).join(" in ") + (e.gpa ? `, GPA ${e.gpa}` : "");
            return `  \\vEntry{${tex(e.school)}}{${range(e.start, e.end)}}{${tex(deg)}}{${tex(e.location)}}\n` + bulletsEnv(e.details, "vBullets");
          })
          .join("") +
        "\\end{vEntries}\n"
      );
    case "skills":
      return (
        H +
        "\\begin{vEntries}\n" +
        r.skills
          .filter((g) => g.items.length)
          .map((g) => `  \\vLine{${g.category ? `\\textbf{${tex(g.category)}:} ` : ""}${tex(g.items.join(", "))}}\n`)
          .join("") +
        "\\end{vEntries}\n"
      );
    case "projects":
      return (
        H +
        "\\begin{vEntries}\n" +
        r.projects
          .map((p) => {
            const title = `\\textbf{${tex(p.name)}}${p.tech ? ` $|$ \\emph{${tex(p.tech)}}` : ""}`;
            const right = range(p.start, p.end) || tex(p.link);
            return `  \\vEntryOne{${title}}{${right}}\n` + bulletsEnv(p.bullets, "vBullets");
          })
          .join("") +
        "\\end{vEntries}\n"
      );
    case "certifications":
      return (
        H +
        "\\begin{vEntries}\n" +
        r.certifications
          .map((c) => `  \\vEntryOne{\\textbf{${tex(c.name)}}${c.issuer ? `, ${tex(c.issuer)}` : ""}}{${month(c.date)}}\n`)
          .join("") +
        "\\end{vEntries}\n"
      );
  }
}
