import { SECTION_HEADINGS, type Resume } from "@/lib/schema";
import { bulletsEnv, contactParts, month, range, README, tex, type LatexOutput } from "./common";

/**
 * "Two-column" style: narrow left column (education, skills, certifications),
 * wide right column (experience, projects). Lato, on paracol so it compiles with pdflatex.
 *
 * Not ATS-safe: sidebar text reads out of order in Workday/Taleo. The app warns.
 */
export function renderColumns(r: Resume): LatexOutput {
  const paper = r.meta.paper === "a4" ? "a4paper" : "letterpaper";
  const [first, ...rest] = r.contact.fullName.trim().split(/\s+/);
  const last = rest.join(" ");

  const left = [
    r.education.length
      ? `\\vSection{${SECTION_HEADINGS.education}}\n` +
        r.education
          .map((e) => {
            const deg = [e.degree, e.field].filter(Boolean).join(" in ");
            return `\\textbf{${tex(e.school)}}\\par\n${tex(deg)}\\par\n{\\small\\color{muted}${range(e.start, e.end)}${e.gpa ? ` \\hspace{3pt}$\\cdot$\\hspace{3pt} GPA ${tex(e.gpa)}` : ""}}\\par\\vspace{6pt}\n`;
          })
          .join("")
      : "",
    r.skills.some((g) => g.items.length)
      ? `\\vSection{${SECTION_HEADINGS.skills}}\n` +
        r.skills
          .filter((g) => g.items.length)
          .map((g) => `${g.category ? `\\textbf{${tex(g.category)}}\\par\n` : ""}{\\small ${g.items.map(tex).join(" $\\cdot$ ")}}\\par\\vspace{6pt}\n`)
          .join("")
      : "",
    r.certifications.length
      ? `\\vSection{${SECTION_HEADINGS.certifications}}\n` +
        r.certifications.map((c) => `\\textbf{${tex(c.name)}}\\par\n{\\small\\color{muted}${[tex(c.issuer), month(c.date)].filter(Boolean).join(" $\\cdot$ ")}}\\par\\vspace{6pt}\n`).join("")
      : "",
  ]
    .filter(Boolean)
    .join("\n");

  const right = [
    r.experience.length
      ? `\\vSection{${SECTION_HEADINGS.experience}}\n` +
        r.experience
          .map(
            (e) =>
              `\\vEntry{${tex(e.title)}}{${range(e.start, e.end, e.current)}}{${tex(e.company)}}{${tex(e.location)}}\n` +
              (bulletsEnv(e.bullets, "vBullets", "") || "\\vspace{4pt}\n"),
          )
          .join("")
      : "",
    r.projects.length
      ? `\\vSection{${SECTION_HEADINGS.projects}}\n` +
        r.projects
          .map((p) => {
            const title = `\\textbf{${tex(p.name)}}${p.tech ? ` {\\color{muted}$|$ ${tex(p.tech)}}` : ""}`;
            return `\\vEntryOne{${title}}{${range(p.start, p.end) || tex(p.link)}}\n` + (bulletsEnv(p.bullets, "vBullets", "") || "\\vspace{4pt}\n");
          })
          .join("")
      : "",
  ]
    .filter(Boolean)
    .join("\n");

  const texSrc = `%% Resume, "Two-column" style, generated by ResumeFold
%% Compile with pdflatex. NOTE: two-column layouts are not ATS-safe.
\\documentclass[${paper},10pt]{article}

\\usepackage[margin=0.5in,top=0.45in,bottom=0.45in]{geometry}
\\usepackage[T1]{fontenc}
\\usepackage[utf8]{inputenc}
\\usepackage[default]{lato}
\\usepackage{xcolor}
\\usepackage{paracol}
\\usepackage{enumitem}
\\usepackage{tabularx}
\\usepackage{microtype}
\\usepackage[hidelinks]{hyperref}
\\input{glyphtounicode}
\\pdfgentounicode=1

\\definecolor{muted}{HTML}{5E5A52}
\\definecolor{rule}{HTML}{222222}
\\pagestyle{empty}
\\setlength{\\parindent}{0pt}
\\setlength{\\tabcolsep}{0pt}
\\setlength{\\columnsep}{0.3in}
\\columnratio{0.3}
\\raggedbottom
\\urlstyle{same}

\\newcommand{\\vSection}[1]{\\par\\vspace{8pt}\\noindent{\\large\\bfseries\\textls[140]{\\MakeUppercase{#1}}}\\par\\vspace{-4pt}\\noindent{\\color{rule}\\rule{\\linewidth}{0.8pt}}\\par\\vspace{4pt}}
\\newcommand{\\vEntry}[4]{%
  \\begin{tabular*}{\\linewidth}{@{}l@{\\extracolsep{\\fill}}r@{}}
    \\textbf{#1} & {\\small\\color{muted}#2}\\\\
    {\\color{muted}#3} & {\\small\\color{muted}#4}\\\\
  \\end{tabular*}\\par}
\\newcommand{\\vEntryOne}[2]{%
  \\begin{tabular*}{\\linewidth}{@{}l@{\\extracolsep{\\fill}}r@{}}
    #1 & {\\small\\color{muted}#2}\\\\
  \\end{tabular*}\\par}
\\newenvironment{vBullets}{\\begin{itemize}[leftmargin=1.1em,itemsep=0pt,topsep=2pt,label=\\textbullet]}{\\end{itemize}\\vspace{4pt}}

\\begin{document}

% ---- header ----
\\begin{tabular*}{\\textwidth}{@{}l@{\\extracolsep{\\fill}}r@{}}
  {\\fontsize{30}{34}\\selectfont {\\fontseries{l}\\selectfont ${tex(first ?? "")}} {\\fontseries{b}\\selectfont ${tex(last)}}} &
  \\begin{tabular}[b]{@{}r@{}}\\small ${contactParts(r).join("\\\\ ")}\\end{tabular}\\\\[4pt]
\\end{tabular*}
{\\color{rule}\\rule{\\textwidth}{1.2pt}}

\\begin{paracol}{2}
${left}
\\switchcolumn
${right}
\\end{paracol}

\\end{document}
`;

  return { files: { "resume.tex": texSrc, "README.md": README("Two-column", "pdflatex") }, main: "resume.tex", engine: "pdflatex" };
}
