import type { Resume } from "@/lib/schema";
import { fmtRange, fmtMonth } from "@/lib/dates";

export type LatexOutput = {
  /** filename → contents */
  files: Record<string, string>;
  main: string;
  engine: "pdflatex" | "xelatex" | "lualatex";
};

/** Escape user text for LaTeX. Order matters: backslash first. */
export function tex(s: string): string {
  return s
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([&%$#_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}")
    .replace(/—/g, "---")
    .replace(/–/g, "--")
    .replace(/[“”]/g, (m) => (m === "“" ? "``" : "''"))
    .replace(/[‘’]/g, (m) => (m === "‘" ? "`" : "'"))
    .replace(/…/g, "\\ldots{}")
    .replace(/</g, "\\textless{}")
    .replace(/>/g, "\\textgreater{}")
    .replace(/\|/g, "\\textbar{}")
    .replace(/[^\x00-\x7F]/g, (ch) => {
      // Let inputenc/utf8 handle common Latin-1; strip anything exotic (emoji) so pdflatex doesn't choke.
      return ch.charCodeAt(0) < 0x250 ? ch : "";
    });
}

export const range = (s: string, e: string, cur = false) => tex(fmtRange(s, e, cur, "--"));
export const month = (s: string) => tex(fmtMonth(s));

/** Wrap a URL-ish string in \href with https:// if needed. Visible text stays as typed (ATS-readable). */
export function href(raw: string): string {
  const t = raw.trim();
  if (!t) return "";
  const url = /^https?:\/\//i.test(t) ? t : `https://${t}`;
  return `\\href{${url.replace(/[%#]/g, (m) => "\\" + m)}}{${tex(t)}}`;
}

export function contactParts(r: Resume): string[] {
  const c = r.contact;
  return [
    c.email ? `\\href{mailto:${c.email}}{${tex(c.email)}}` : "",
    tex(c.phone),
    tex(c.location),
    href(c.website),
    href(c.linkedin),
    href(c.github),
  ].filter(Boolean);
}

export function bulletsEnv(items: string[], env: string, indent = "    "): string {
  const list = items.filter((b) => b.trim());
  if (!list.length) return "";
  return `${indent}\\begin{${env}}\n${list.map((b) => `${indent}  \\item ${tex(b)}`).join("\n")}\n${indent}\\end{${env}}\n`;
}

export const README = (style: string, engine: string) => `# Resume, ${style} style

Generated by ResumeFold. Compile with ${engine}:

    ${engine} resume.tex

Or open the .tex on Overleaf (Menu → Compiler → ${engine}).

The style is an original reimplementation; no template code was copied.
All content is yours.
`;
